language: python

python:
  - "2.7"

before_install:
  - sudo add-apt-repository "deb http://mirrors.kernel.org/ubuntu zesty main universe"
  - sudo apt-get update
  - sudo apt-get install $(cat deb_reqs.txt)

install:
  - pip install unittest2

script:
  - python kim/tests/test_speech.py